### PR TITLE
Fix creating static forwarders for inherited methods

### LINKED ISSUE #154: genjavadoc produces static public abstract methods
Ref https://github.com/akka/akka/pull/26050
Ref https://github.com/akka/akka/issues/26057

### steps

Given https://github.com/akka/akka/blob/v2.5.18/akka-actor-typed/src/main/scala/akka/actor/typed/Props.scala

```scala
package akka.actor.typed

abstract class Props private[akka] () extends Product with Serializable {
  private[akka] def next: Props
}

sealed abstract class DispatcherSelector extends Props
```

## problem

It seems like sbt-unidoc is currently producing DispatcherSelector.java:34:

```java
static public abstract  akka.actor.typed.Props next ()  ;
```

sbt 1.2.7's Javadoc is no longer able to compile this.

## expectations

Produce valid Java methods, for example without `static` modifier.

### PR DESCRIPTION
**Pull request by raboof**
We should create static forwarders for the methods inherited on the
companion object, not on the class itself.

Fixes #154

### CODE REVIEW

**Comment by raboof** [comment]
I just confirmed this change fixed #154 in the Akka build, though other problems remain.

File: plugin/src/test/resources/expected_output/basic/akka/actor/Identify.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package akka.actor;
+public final class Identify implements scala.Product, scala.Serializable {
+  static public  akka.actor.Identify apply (Object messageId)  { throw new RuntimeException(); }
+  static public  scala.Option<java.lang.Object> unapply (akka.actor.Identify x$0)  { throw new RuntimeException(); }
+  static private  java.lang.Object readResolve ()  { throw new RuntimeException(); }
+  public  Object messageId ()  { throw new RuntimeException(); }
+  // not preceding
+  public   Identify (Object messageId)  { throw new RuntimeException(); }
+  public  akka.actor.Identify copy (Object messageId)  { throw new RuntimeException(); }
+  public  Object copy$default$1 ()  { throw new RuntimeException(); }
```
Comment (patriknw) [inline plugin/src/test/resources/expected_output/basic/akka/actor/Identify.java]: a nice thing for the future could be to completely filter out Scala stuff that's not intended to be public Java API
